///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lights
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LightsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("29f64987-f249-458e-8d6c-db51c9bfb0fe")]
    public partial class LightsRepository : RepoGenBaseFolder
    {
        static LightsRepository instance = new LightsRepository();
        LightsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;

        /// <summary>
        /// Gets the singleton class instance representing the LightsRepository element repository.
        /// </summary>
        [RepositoryFolder("29f64987-f249-458e-8d6c-db51c9bfb0fe")]
        public static LightsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LightsRepository() 
            : base("LightsRepository", "/", null, 0, false, "29f64987-f249-458e-8d6c-db51c9bfb0fe", ".\\RepositoryImages\\LightsRepository29f64987.rximgres")
        {
            _snapxuntitled = new LightsRepositoryFolders.SnapXUntitledAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("29f64987-f249-458e-8d6c-db51c9bfb0fe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("bbfa4216-fd0e-4577-8eec-e506f09faa6d")]
        public virtual LightsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class LightsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("bbfa4216-fd0e-4577-8eec-e506f09faa6d")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            LightsRepositoryFolders.Container59648Folder _container59648;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "bbfa4216-fd0e-4577-8eec-e506f09faa6d", "")
            {
                _container59648 = new LightsRepositoryFolders.Container59648Folder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bbfa4216-fd0e-4577-8eec-e506f09faa6d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bbfa4216-fd0e-4577-8eec-e506f09faa6d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Container59648 folder.
            /// </summary>
            [RepositoryFolder("e71168c8-7fb4-4db8-be3e-f276b5310e52")]
            public virtual LightsRepositoryFolders.Container59648Folder Container59648
            {
                get { return _container59648; }
            }
        }

        /// <summary>
        /// The Container59648Folder folder.
        /// </summary>
        [RepositoryFolder("e71168c8-7fb4-4db8-be3e-f276b5310e52")]
        public partial class Container59648Folder : RepoGenBaseFolder
        {
            RepoItemInfo _backlightffwInfo;
            RepoItemInfo _backlightbigmodeInfo;
            RepoItemInfo _switchfrombigtoffwInfo;
            RepoItemInfo _switchfromffwtobigInfo;
            RepoItemInfo _surfacelightbigmodeInfo;
            RepoItemInfo _surfacelightffwInfo;
            RepoItemInfo _srlbigmodeInfo;
            RepoItemInfo _srlffwInfo;
            SRLSliderInfoClass _srlsliderInfo;
            SurfaceSliderInfoClass _surfacesliderInfo;
            BackSliderInfoClass _backsliderInfo;
            RepoItemInfo _boostffwInfo;
            RepoItemInfo _boostbigmodeInfo;
            SRLImageFFWInfoClass _srlimageffwInfo;
            SurfaceImageFFWInfoClass _surfaceimageffwInfo;
            BackImageFFWInfoClass _backimageffwInfo;

            /// <summary>
            /// Creates a new Container59648  folder.
            /// </summary>
            public Container59648Folder(RepoGenBaseFolder parentFolder) :
                    base("Container59648", "container[@controlid='59648']", parentFolder, 30000, null, false, "e71168c8-7fb4-4db8-be3e-f276b5310e52", "")
            {
                _backlightffwInfo = new RepoItemInfo(this, "BackLightFFW", "form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1017']", 30000, null, "2b99fed4-8d70-4cea-b8a1-946df10a6b57");
                _backlightbigmodeInfo = new RepoItemInfo(this, "BackLightBigMode", "form//text[@controlid='1017']", 30000, null, "f5d08b2f-0dab-4ca9-a891-4c9712673e3d");
                _switchfrombigtoffwInfo = new RepoItemInfo(this, "SwitchFromBigToFFW", "form//toolbar[@class='ToolbarWindow32']/button[@commandid='40028']", 30000, null, "62631786-bdbd-4c71-8837-a8f882dd6992");
                _switchfromffwtobigInfo = new RepoItemInfo(this, "SwitchFromFFWToBig", "form/?/?/element/element/toolbar/button[@commandid='40029']", 30000, null, "64b276f9-74c7-477e-b359-bf9294409886");
                _surfacelightbigmodeInfo = new RepoItemInfo(this, "SurfaceLightBigMode", "form[@controlid='65281']//text[@controlid='1018']", 30000, null, "3ddfe7e2-b3cf-410f-bb2b-f13ca30dab76");
                _surfacelightffwInfo = new RepoItemInfo(this, "SurfaceLightFFW", "form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1018']", 30000, null, "0782b0cf-26b8-4adf-8960-ba1cfafdfc0b");
                _srlbigmodeInfo = new RepoItemInfo(this, "SRLBigMode", "form[@controlid='65281']//text[@controlid='1015']", 30000, null, "245dbc65-0b63-4794-8844-5311bf28427e");
                _srlffwInfo = new RepoItemInfo(this, "SRLFFW", "form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1015']", 30000, null, "dceefa5f-d28d-487a-9ff3-17431b3177b5");
                _srlsliderInfo = new SRLSliderInfoClass(this);
                _surfacesliderInfo = new SurfaceSliderInfoClass(this);
                _backsliderInfo = new BackSliderInfoClass(this);
                _boostffwInfo = new RepoItemInfo(this, "BoostFFW", "form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1012']", 30000, null, "24270176-0c40-407e-b10f-199d1cb738c9");
                _boostbigmodeInfo = new RepoItemInfo(this, "BoostBigMode", "form[@controlid='65281']//text[@controlid='1012']", 30000, null, "1d90b1ee-f5a3-4cac-9e8b-d96d4de28f63");
                _srlimageffwInfo = new SRLImageFFWInfoClass(this);
                _surfaceimageffwInfo = new SurfaceImageFFWInfoClass(this);
                _backimageffwInfo = new BackImageFFWInfoClass(this);
            }

            /// <summary>
            /// The SRLSliderInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("452a560a-dfc5-4af3-ab54-df3ef3a9cdfe")]
            public class SRLSliderInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SRLSliderInfoClass class constructor.
                /// </summary>
                public SRLSliderInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SRLSlider", "form//slider[@controlid='4115']", 30000, null, "452a560a-dfc5-4af3-ab54-df3ef3a9cdfe")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("9d956714-8673-42f9-9625-19e1455b9737")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("9d956714-8673-42f9-9625-19e1455b9737");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("9d956714-8673-42f9-9625-19e1455b9737")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("9d956714-8673-42f9-9625-19e1455b9737", cropRect);
                }
            }

            /// <summary>
            /// The SurfaceSliderInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9d31a0fb-b157-45c1-b0e7-2970b994eb3a")]
            public class SurfaceSliderInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SurfaceSliderInfoClass class constructor.
                /// </summary>
                public SurfaceSliderInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SurfaceSlider", "form//slider[@controlid='4112']", 30000, null, "9d31a0fb-b157-45c1-b0e7-2970b994eb3a")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("35a10a0b-cf86-418b-8e1a-591a8fec9d3c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("35a10a0b-cf86-418b-8e1a-591a8fec9d3c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("35a10a0b-cf86-418b-8e1a-591a8fec9d3c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("35a10a0b-cf86-418b-8e1a-591a8fec9d3c", cropRect);
                }
            }

            /// <summary>
            /// The BackSliderInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("932d8258-c4ea-4277-bfc8-92c5a64d2faa")]
            public class BackSliderInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BackSliderInfoClass class constructor.
                /// </summary>
                public BackSliderInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "BackSlider", "form//slider[@controlid='4117']", 30000, null, "932d8258-c4ea-4277-bfc8-92c5a64d2faa")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("2de6aa91-6f6b-4977-9b96-3c81af88439f")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("2de6aa91-6f6b-4977-9b96-3c81af88439f");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2de6aa91-6f6b-4977-9b96-3c81af88439f")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2de6aa91-6f6b-4977-9b96-3c81af88439f", cropRect);
                }
            }

            /// <summary>
            /// The SRLImageFFWInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("1660551c-9cde-4bae-9109-e403aab36d79")]
            public class SRLImageFFWInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SRLImageFFWInfoClass class constructor.
                /// </summary>
                public SRLImageFFWInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SRLImageFFW", "form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1008']", 30000, null, "1660551c-9cde-4bae-9109-e403aab36d79")
                { }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("012bfc1e-7e72-4697-9a28-f3ff1e66303c")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("012bfc1e-7e72-4697-9a28-f3ff1e66303c");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("012bfc1e-7e72-4697-9a28-f3ff1e66303c")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("012bfc1e-7e72-4697-9a28-f3ff1e66303c", cropRect);
                }
            }

            /// <summary>
            /// The SurfaceImageFFWInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("cb616301-7567-4343-a859-86bb184acdf8")]
            public class SurfaceImageFFWInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SurfaceImageFFWInfoClass class constructor.
                /// </summary>
                public SurfaceImageFFWInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SurfaceImageFFW", "form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1011']", 30000, null, "cb616301-7567-4343-a859-86bb184acdf8")
                { }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("4bd8910b-60a0-4f24-8e65-eaacd95a97a9")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("4bd8910b-60a0-4f24-8e65-eaacd95a97a9");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("4bd8910b-60a0-4f24-8e65-eaacd95a97a9")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("4bd8910b-60a0-4f24-8e65-eaacd95a97a9", cropRect);
                }
            }

            /// <summary>
            /// The BackImageFFWInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("bcb1fad5-117d-465d-a94c-22f365eb56c2")]
            public class BackImageFFWInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BackImageFFWInfoClass class constructor.
                /// </summary>
                public BackImageFFWInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "BackImageFFW", "form//element[@controlid='59648']/container[@class='#32770']/text[@controlid='1010']", 30000, null, "bcb1fad5-117d-465d-a94c-22f365eb56c2")
                { }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("52070a31-448a-412e-b794-eb246ca7f9ae")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("52070a31-448a-412e-b794-eb246ca7f9ae");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("52070a31-448a-412e-b794-eb246ca7f9ae")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("52070a31-448a-412e-b794-eb246ca7f9ae", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e71168c8-7fb4-4db8-be3e-f276b5310e52")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e71168c8-7fb4-4db8-be3e-f276b5310e52")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BackLightFFW item.
            /// </summary>
            [RepositoryItem("2b99fed4-8d70-4cea-b8a1-946df10a6b57")]
            public virtual Ranorex.Text BackLightFFW
            {
                get
                {
                    return _backlightffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BackLightFFW item info.
            /// </summary>
            [RepositoryItemInfo("2b99fed4-8d70-4cea-b8a1-946df10a6b57")]
            public virtual RepoItemInfo BackLightFFWInfo
            {
                get
                {
                    return _backlightffwInfo;
                }
            }

            /// <summary>
            /// The BackLightBigMode item.
            /// </summary>
            [RepositoryItem("f5d08b2f-0dab-4ca9-a891-4c9712673e3d")]
            public virtual Ranorex.Text BackLightBigMode
            {
                get
                {
                    return _backlightbigmodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BackLightBigMode item info.
            /// </summary>
            [RepositoryItemInfo("f5d08b2f-0dab-4ca9-a891-4c9712673e3d")]
            public virtual RepoItemInfo BackLightBigModeInfo
            {
                get
                {
                    return _backlightbigmodeInfo;
                }
            }

            /// <summary>
            /// The SwitchFromBigToFFW item.
            /// </summary>
            [RepositoryItem("62631786-bdbd-4c71-8837-a8f882dd6992")]
            public virtual Ranorex.Button SwitchFromBigToFFW
            {
                get
                {
                    return _switchfrombigtoffwInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchFromBigToFFW item info.
            /// </summary>
            [RepositoryItemInfo("62631786-bdbd-4c71-8837-a8f882dd6992")]
            public virtual RepoItemInfo SwitchFromBigToFFWInfo
            {
                get
                {
                    return _switchfrombigtoffwInfo;
                }
            }

            /// <summary>
            /// The SwitchFromFFWToBig item.
            /// </summary>
            [RepositoryItem("64b276f9-74c7-477e-b359-bf9294409886")]
            public virtual Ranorex.Button SwitchFromFFWToBig
            {
                get
                {
                    return _switchfromffwtobigInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchFromFFWToBig item info.
            /// </summary>
            [RepositoryItemInfo("64b276f9-74c7-477e-b359-bf9294409886")]
            public virtual RepoItemInfo SwitchFromFFWToBigInfo
            {
                get
                {
                    return _switchfromffwtobigInfo;
                }
            }

            /// <summary>
            /// The SurfaceLightBigMode item.
            /// </summary>
            [RepositoryItem("3ddfe7e2-b3cf-410f-bb2b-f13ca30dab76")]
            public virtual Ranorex.Text SurfaceLightBigMode
            {
                get
                {
                    return _surfacelightbigmodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SurfaceLightBigMode item info.
            /// </summary>
            [RepositoryItemInfo("3ddfe7e2-b3cf-410f-bb2b-f13ca30dab76")]
            public virtual RepoItemInfo SurfaceLightBigModeInfo
            {
                get
                {
                    return _surfacelightbigmodeInfo;
                }
            }

            /// <summary>
            /// The SurfaceLightFFW item.
            /// </summary>
            [RepositoryItem("0782b0cf-26b8-4adf-8960-ba1cfafdfc0b")]
            public virtual Ranorex.Text SurfaceLightFFW
            {
                get
                {
                    return _surfacelightffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SurfaceLightFFW item info.
            /// </summary>
            [RepositoryItemInfo("0782b0cf-26b8-4adf-8960-ba1cfafdfc0b")]
            public virtual RepoItemInfo SurfaceLightFFWInfo
            {
                get
                {
                    return _surfacelightffwInfo;
                }
            }

            /// <summary>
            /// The SRLBigMode item.
            /// </summary>
            [RepositoryItem("245dbc65-0b63-4794-8844-5311bf28427e")]
            public virtual Ranorex.Text SRLBigMode
            {
                get
                {
                    return _srlbigmodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SRLBigMode item info.
            /// </summary>
            [RepositoryItemInfo("245dbc65-0b63-4794-8844-5311bf28427e")]
            public virtual RepoItemInfo SRLBigModeInfo
            {
                get
                {
                    return _srlbigmodeInfo;
                }
            }

            /// <summary>
            /// The SRLFFW item.
            /// </summary>
            [RepositoryItem("dceefa5f-d28d-487a-9ff3-17431b3177b5")]
            public virtual Ranorex.Text SRLFFW
            {
                get
                {
                    return _srlffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SRLFFW item info.
            /// </summary>
            [RepositoryItemInfo("dceefa5f-d28d-487a-9ff3-17431b3177b5")]
            public virtual RepoItemInfo SRLFFWInfo
            {
                get
                {
                    return _srlffwInfo;
                }
            }

            /// <summary>
            /// The SRLSlider item.
            /// </summary>
            [RepositoryItem("452a560a-dfc5-4af3-ab54-df3ef3a9cdfe")]
            public virtual Ranorex.Slider SRLSlider
            {
                get
                {
                    return _srlsliderInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The SRLSlider item info.
            /// </summary>
            [RepositoryItemInfo("452a560a-dfc5-4af3-ab54-df3ef3a9cdfe")]
            public virtual SRLSliderInfoClass SRLSliderInfo
            {
                get
                {
                    return _srlsliderInfo;
                }
            }

            /// <summary>
            /// The SurfaceSlider item.
            /// </summary>
            [RepositoryItem("9d31a0fb-b157-45c1-b0e7-2970b994eb3a")]
            public virtual Ranorex.Slider SurfaceSlider
            {
                get
                {
                    return _surfacesliderInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The SurfaceSlider item info.
            /// </summary>
            [RepositoryItemInfo("9d31a0fb-b157-45c1-b0e7-2970b994eb3a")]
            public virtual SurfaceSliderInfoClass SurfaceSliderInfo
            {
                get
                {
                    return _surfacesliderInfo;
                }
            }

            /// <summary>
            /// The BackSlider item.
            /// </summary>
            [RepositoryItem("932d8258-c4ea-4277-bfc8-92c5a64d2faa")]
            public virtual Ranorex.Slider BackSlider
            {
                get
                {
                    return _backsliderInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The BackSlider item info.
            /// </summary>
            [RepositoryItemInfo("932d8258-c4ea-4277-bfc8-92c5a64d2faa")]
            public virtual BackSliderInfoClass BackSliderInfo
            {
                get
                {
                    return _backsliderInfo;
                }
            }

            /// <summary>
            /// The BoostFFW item.
            /// </summary>
            [RepositoryItem("24270176-0c40-407e-b10f-199d1cb738c9")]
            public virtual Ranorex.Text BoostFFW
            {
                get
                {
                    return _boostffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BoostFFW item info.
            /// </summary>
            [RepositoryItemInfo("24270176-0c40-407e-b10f-199d1cb738c9")]
            public virtual RepoItemInfo BoostFFWInfo
            {
                get
                {
                    return _boostffwInfo;
                }
            }

            /// <summary>
            /// The BoostBigMode item.
            /// </summary>
            [RepositoryItem("1d90b1ee-f5a3-4cac-9e8b-d96d4de28f63")]
            public virtual Ranorex.Text BoostBigMode
            {
                get
                {
                    return _boostbigmodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BoostBigMode item info.
            /// </summary>
            [RepositoryItemInfo("1d90b1ee-f5a3-4cac-9e8b-d96d4de28f63")]
            public virtual RepoItemInfo BoostBigModeInfo
            {
                get
                {
                    return _boostbigmodeInfo;
                }
            }

            /// <summary>
            /// The SRLImageFFW item.
            /// </summary>
            [RepositoryItem("1660551c-9cde-4bae-9109-e403aab36d79")]
            public virtual Ranorex.Text SRLImageFFW
            {
                get
                {
                    return _srlimageffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SRLImageFFW item info.
            /// </summary>
            [RepositoryItemInfo("1660551c-9cde-4bae-9109-e403aab36d79")]
            public virtual SRLImageFFWInfoClass SRLImageFFWInfo
            {
                get
                {
                    return _srlimageffwInfo;
                }
            }

            /// <summary>
            /// The SurfaceImageFFW item.
            /// </summary>
            [RepositoryItem("cb616301-7567-4343-a859-86bb184acdf8")]
            public virtual Ranorex.Text SurfaceImageFFW
            {
                get
                {
                    return _surfaceimageffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SurfaceImageFFW item info.
            /// </summary>
            [RepositoryItemInfo("cb616301-7567-4343-a859-86bb184acdf8")]
            public virtual SurfaceImageFFWInfoClass SurfaceImageFFWInfo
            {
                get
                {
                    return _surfaceimageffwInfo;
                }
            }

            /// <summary>
            /// The BackImageFFW item.
            /// </summary>
            [RepositoryItem("bcb1fad5-117d-465d-a94c-22f365eb56c2")]
            public virtual Ranorex.Text BackImageFFW
            {
                get
                {
                    return _backimageffwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BackImageFFW item info.
            /// </summary>
            [RepositoryItemInfo("bcb1fad5-117d-465d-a94c-22f365eb56c2")]
            public virtual BackImageFFWInfoClass BackImageFFWInfo
            {
                get
                {
                    return _backimageffwInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}